# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7bd1c3d74c8cb3d7aaa99f2b8c9c9b1cd55b42ce00889d0c014649cd6af12790197f6e219fa6f0054231d092f19ef79268f18ba55b50c4a04d9621a11ef41f0

test:
  secret_key_base: a0e522c73eb48fda4ab3d071f522755a9becfc25f4302f50879ec208d225f31a360e308163cfb24b4e4dc999c50c83a1f52ca97e2d0e10e00c33bad38948a0ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
